### ISSUE TITLE
Tracking: Networking Crate

### ISSUE THREAD

**Issue by refcell** [ithacaxyz/op-rs#70]
### Description

A tracking issue for the `net` crate - consensus layer networking types, builders, and drivers.
```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/op-rs/issues/6
- [ ] https://github.com/paradigmxyz/op-rs/issues/36
- [ ] https://github.com/paradigmxyz/op-rs/issues/38
- [ ] https://github.com/paradigmxyz/op-rs/issues/39
- [ ] https://github.com/paradigmxyz/op-rs/issues/52
- [ ] https://github.com/paradigmxyz/op-rs/issues/40
- [ ] https://github.com/paradigmxyz/op-rs/issues/51
- [ ] https://github.com/paradigmxyz/op-rs/issues/68
- [ ] https://github.com/paradigmxyz/op-rs/issues/69
```
